### ISSUE TITLE
[Godot] Which Vector is Up?

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#17]
We need to check / research which axis will be the up vector in Godot.  This is important since it will influence our geometry.

**Comment by kevinmatthes** [comment]
I will upload an upright cuboid in a separate repository within this namespace, soon.  With it, we can test whether y or z is the up vector.

**Comment by kevinmatthes** [comment]
@Ranplax:  please use the repository for your sample geometry, as well.  I will tell you its path as soon as I created it.

**Comment by Luka-sama** [comment]
I have researched and checked, Godot has Y-axis as up vector.

**Comment by kevinmatthes** [comment]
Okay, thank you!  Please note down this fact somewhere in this repository (perhaps a separate documentation file for Godot issues) for future reference.
