### ISSUE TITLE
[Geometry] Create Basic Geometry for Jupiter and Saturn

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#18]
@Ranplax:  please create some geometry for Jupiter and Saturn.  Glue some procedural / image texture on it.  Upload it to the geometry repository of our project's namespace.  For the beginning, please just check-in your Blender projects.  (Only main file, no backup files, please.  Adjust your `.gitignore`, if required.)

Here is a checklist:

* [x] Create geometry for Jupiter.
* [x] Create geometry for Saturn.
* [ ] Create geometry for default moons.
* [ ] Create geometry for default asteroids.
* [x] Add some procedural textures for Jupiter.
* [x] Add some procedural textures for Saturn.
* [x] Add some procedural textures for Jupiter's main moons.
* [ ] Add some procedural textures for the default asteroids.

I know that there is no such repository, at the moment.  I will create it soon and tell you the path to it.

**Comment by kevinmatthes** [comment]
@Ranplax: <https://github.com/StarSimVR/blender-projects>  Check-in your Blender files here, please.

**Comment by kevinmatthes** [comment]
**DEFINITION OF DONE**:  the named objects are available in of our repositories as a set of geometry files with some textures.

**Comment by NiklasLeukroth** [comment]
This issue became obsolete due to an upcoming implementation of procedural geometry using the godot engine
