### ISSUE TITLE
[Documentation] Upload Your Sample Applications to this Namespace

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#29]
Please upload your sample applications to our project's namespace for future reference, if possible.

* [x] @Luka-sama 
* [x] @Ranplax

**Comment by Luka-sama** [comment]
Do you mean create a new repository, or would a [commit link](https://github.com/StarSimVR/godot/tree/239d5291dae94d9e3a4b926d1b4d59bdcd3f9798) be enough?

**Comment by kevinmatthes** [comment]
I assumed that the sample application would require a repository on its own.  In this case, it is just an expansion of an already existing one.  Everything is alright, you do not need to upload anything further.
