### ISSUE TITLE
[Maths] [ellipse] Solve Linking Problems on Windows

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#35]
We need to solve the ongoing problems when linking `libellipse.a` with our further project code on Windows.

@Ranplax, please try to introduce features such that the library can be compiled to a DLL for Windows.  I just forked the library to my namespace such that you do not need to worry in case errors should occur.  I can recreate the library from my namespace in case something should go wrong.

If you would like to experiment with the library, please consider to fork it to your namespace, as well.

In any case, please add your name to all license notices of the library.

**Comment by NiklasLeukroth** [comment]
The dll implementation is pushed on the dlltesting branch, the following neccesarry steps have been moved into issue #43
