### ISSUE TITLE
[Godot] Add Adjustment Interface to Godot

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#36]
Please adjust the Godot variable editing interface such that the further parameters of the `Ellipse` class might be adjusted, as well.  These are:

* [ ] centre (`cx`, `cy`, `cz`)
* [ ] normal (`nx`, `ny`, `nz`)
* [ ] tangent (`tx`, `ty`, `tz`)

Furthermore, please name all script variables intuitive (`Radius` instead of `R`, `Eccentricity` instead of `E`).  My suggestion for the name is `Centre (x)` or something like that.

**Comment by Luka-sama** [comment]
The interface is ready:

![grafik](https://user-images.githubusercontent.com/91343355/147136144-7d7da417-41e9-4b3f-bdaa-016024c2f196.png)
