### ISSUE TITLE
[Godot] Research Sync of Script Variables with Godot

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#38]
We need to know how to keep Script Variables and Transformation properties in sync.

**Comment by Luka-sama** [comment]
Synchronization is ready. You can edit `GDMath::sync_transform` and `GDMath::sync_math` to achieve the desired behavior. At the moment, the code is like this:

```
void GDMath::sync_transform() {
	set_translation(center);
}

void GDMath::sync_math() {
	center = get_translation();
}
```
