### ISSUE TITLE
[Maths] [ellipse] Switch Build Routine to GNU Octave

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#40]
Since we need GNU Octave in any case, we can also build our libraries with Octave directly instead of employing `make` therefore.  This also benefits the portability.

**Comment by kevinmatthes** [comment]
@Ranplax, @Luka-sama:  please make sure to have GNU Octave installed in order to build the `ellipse` library.

**Comment by kevinmatthes** [comment]
@Ranplax, @Luka-sama:  please check whether the installation routine of https://github.com/kevinmatthes/cogeo-formulae works for you (despite `tidy.m` which requires the UNIX `test` command, see #41).

**Comment by Luka-sama** [comment]
Yes, it works.

**Comment by kevinmatthes** [comment]
Great!

I prepared some initial scripts in https://github.com/kevinmatthes/routines and will incorporate them into my fork of `ellipse`.  Some scripts are still missing, I am going to add them, as well.
