### ISSUE TITLE
[General] Test Command on Windows?

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#41]
Is there any portable alternative to the UNIX `test` command on Windows?  I would need it especially for `libellipse.a` ...

**Comment by NiklasLeukroth** [comment]
I have contacted my friend and we will be working on the implementation the coming week.

**Comment by kevinmatthes** [comment]
@Ranplax:  Please create a separate repository for the script such that we can fork it to our project.

**Comment by kevinmatthes** [comment]
Thank you!
