### ISSUE TITLE
[3D-Scene] Keyboard Layout

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#49]
Please add a brief documentation of the current keyboard layout to the backlog.

**Comment by kevinmatthes** [comment]
@Luka-sama, is there a possibility to render something like a cheat sheet directly from the Godot key mapping interface?

**Comment by Luka-sama** [comment]
> @Luka-sama, is there a possibility to render something like a cheat sheet directly from the Godot key mapping interface?

Yes, it is possible. Done with [this commit](https://github.com/StarSimVR/godot/commit/23154cb9c152157900f538d56807b0150706ae49).
