### ISSUE TITLE
[VR] Add Geometry of Astronomic Objects

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#5]
Our scene seems to be quite empty, at the moment.  We should define geometry of the astronomic objects we want to visualise in order to fix this.

**Comment by kevinmatthes** [comment]
Basically, should we rather use Wavefront or STL geometry?

The first one can be edited more freely, the latter one more precisely.

**Comment by kevinmatthes** [comment]
In addition to the previous post:

STL geometry can be converted to Wavefront by importing in Blender and re-exporting as Wavefront.  As long as the geometry is still compilable, we are quite free to choose.  But the other way around, to import Wavefront models to STL editors, does not seem to work, as far as I know.

@Ranplax:  how to import geometry to the VR application?  Are there any restrictions we need to take care about?

**Comment by thga489** [comment]
salut

**Comment by kevinmatthes** [comment]
The basic geometry will be Jupiter and Saturn models, for the beginning.  We will focus on Jupiter, at first.  @Ranplax
