### ISSUE TITLE
[General] cat Command on Windows?

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#57]
I will need to call UNIX `cat` during the build of the documentation of `ellipse`.  Does this command exist on Windows, as well?

**Comment by NiklasLeukroth** [comment]
The windows equivalent is type, however i do not know whether every single functionality of cat is also supported using type.

**Comment by kevinmatthes** [comment]
UNIX `cat` reads out the given paths and writes their content to `stdout` or -- in case that there is a pipe -- `stdin` of the succeeding application.

Are you **really** sure that Windows `type` does this, as well?

**Comment by NiklasLeukroth** [comment]
No, as i said. Type is the closest thing on windows, printing the content of a file onto the shell.
Using this as input to another application is not supported, if I am not mistaking. Read the official documentation here: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/type

**Comment by kevinmatthes** [comment]
The original `cat` is defined here: https://github.com/coreutils/coreutils/blob/master/src/cat.c

**Comment by kevinmatthes** [comment]
So, basically both `cat` and `type` will work in GNU Octave on Windows.
