### ISSUE TITLE
[License] [VR] Which License do the Meshes Have?

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#60]
We need to research the license of the SteamVR meshes.

**Comment by NiklasLeukroth** [comment]
I will write an email to valve, hoping to get clearence on this issue.

**Comment by kevinmatthes** [comment]
@Ranplax, if I understood you correct, this issue is obsolete, now, right?  If so, please close it and post your research results to this issue for documentation and later reference.

**Comment by NiklasLeukroth** [comment]
The current status is, that in the godot port of steams openVR, not every controller mesh is supported, for instance the vive pro controller that we are currently using cannot be displayed. Therefor i will create a seperate mesh for the controller, where we can also directly map the description onto.
