### ISSUE TITLE
[VR] Reduce motion sickness while teleporting

### ISSUE THREAD

**Issue by NiklasLeukroth** [StarSimVR/backlog#65]
This issue tracks the developement and research of reducing motion sickness caused by the teleportation

Definition of Done: I no longer feel sick when teleporting

**Comment by kevinmatthes** [comment]
Would it be possible to change the brightness of the screens temporarily to zero during the teleport?  Think of it as closing your eyes slowly, teleport and open your eyes carefully again when arriving on the target point.

Does this suggestion would have any effect regarding the negative effects of teleportation?

**Comment by kevinmatthes** [comment]
By the way:  could you please add a "Definition of Done" for this issue, i. e. when is this issue is completed for you?  This would help keeping the focus on the points we might need to work on.  Just post a matching comment to this issue -- that would suffice.

**Comment by kevinmatthes** [comment]
@Ranplax, what is the latest strategy to take care about this problem?

**Comment by NiklasLeukroth** [comment]
Since the motion sickness cannot really be prevented using warp points, a "god view" has been implemented, from which u can choose where to got next, which helps with this problem
