### ISSUE TITLE
[Maths] Class for Astronomic Objects

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#68]
We need to define a class for astronomic objects.  First of all, we should take care about the attributes to consider.

**Comment by kevinmatthes** [comment]
My suggestions:

* mass
* radius (object)
* radius (movement curve)
* rotation duration (object)
* rotation duration (movement curve)
* up vector
* front vector
* eccentricity

**Comment by NiklasLeukroth** [comment]
In my opinion the following would also be useful:

- Name
- Primary Material
- Speed 
- Directional Vector

Meanwhile for the finished product we can probably neglect the following:

- radius (movement curve)
- rotation duration (movement curve)
- eccentricity

**Comment by kevinmatthes** [comment]
As @Luka-sama just mentioned, we could also add the following:

* dark energy
* dark matter

**Comment by kevinmatthes** [comment]
Maybe the current position, as well?

**Comment by NiklasLeukroth** [comment]
Since the mass and size will not change once the scene is "started", it would be useful to precalculate and store the radius of influence of an object, so that we can easily determine which objects to consider on a step to step basis.

**Comment by kevinmatthes** [comment]
I thought exactly the mass and size shall be adjustable -- in addition to the objects' positions?

I am totally fine with precomputation, preferably during the construction of an object.  But I think we should also allow the sizes and masses to be manipulated since this would make the simulation more interesting in the sense of "What if ... ?".

Maybe we could set the masses and radii to constant values for a while until we implemented a stable manipulation interface but I still think that just moving the objects around is perhaps only a starting point.

**Comment by kevinmatthes** [comment]
This issue is related to #70.  If we know which input possibilities we have, we can design a rough plan for the manipulation, especially regarding the attributes we allow to be editable.

**Comment by kevinmatthes** [comment]
Okay, we have got our initial set of attributes for the class, so I am going to implement it.

**Comment by kevinmatthes** [comment]
The development happens in https://github.com/StarSimVR/astobj.
