### ISSUE TITLE
[VR] User Interaction with Controllers

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#70]
Just for documentation, it would be nice to have an overview about the buttons and input methods of / for the controllers.

With "input methods" I mean the answer to the following question:  can this button just be clicked or does it also recognise gestures?  For instance like the scrolling gestures of laptop track pads.

**Comment by NiklasLeukroth** [comment]
A description of the currently supported controller interactions has been added in the readme of the godot repository. Displaying this description goes hand in hand with issue #77, therefore the further progress will be tracked there.
