### ISSUE TITLE
[Maintenance] Namespace Clean-up

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#80]
There are several repositories in our namespace which we do not require anymore.  I would like to suggest to remove them.

In the following, I am going to suggest the repositories to remove.  If you support the suggestion to remove it, please mark the respective comment with :heavy_check_mark:, if you are against it, please use :x: instead.

@Ranplax @Luka-sama

**Comment by kevinmatthes** [comment]
https://github.com/StarSimVR/testOnWindows

**Comment by kevinmatthes** [comment]
I am sorry, due to GitHub's limitation regarding the emoticons to react with, please use :+1: for :heavy_check_mark: and :-1: for :x:, respectively.

**Comment by NiklasLeukroth** [comment]
I would also suggest
https://github.com/StarSimVR/libRnfpp

**Comment by NiklasLeukroth** [comment]
And
https://github.com/StarSimVR/ellipse

**Comment by kevinmatthes** [comment]
I would like to suggest to wait with ellipse since we might need them in a future revision again.

**Comment by kevinmatthes** [comment]
I marked the deleted repositories with :tada:.

**Comment by NiklasLeukroth** [comment]
Star Data?
https://github.com/StarSimVR/star-data

**Comment by kevinmatthes** [comment]
Originally, `star-data` was planned for the `matlab_ephemeris.py` script.  How about storing our scenes there?

**Comment by kevinmatthes** [comment]
I just tagged `ellipse` with :+1:.  We now need one further :+1: for the removal.  @Luka-sama, how about you -- should we keep `ellipse` or do you agree on deleting it?

**Comment by kevinmatthes** [comment]
I just deleted the fork of my CFF citing tool as well as ellipse.  Both are deprecated.  My CFF citing tool will receive a major maintenance in the next months.  I will fork the maintained version if required once all changes are done.
