### ISSUE TITLE
[Enhancement Suggestion] Dependabot for Automatic Submodule Updates

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/backlog#81]
Dependabot is a GitHub App which automatically suggests updates for configured dependencies.  These include GitHub Actions as well as Git sub-modules.  I tried it out with some sample repositories and in my opinion, this is a very useful utility in order to save development time.

If one updates the geometry, for instance, Dependabot will raise a Pull Request which will update the geometry sub-module in the Godot repository.  That way, this update cannot be forgotten as the software will take care about it and one can continue to develop the project without needing to update the sub-module oneself.  The sole requirement is a simple setup which I can do for all concerning repositories of our namespace.

Are you interested, @Ranplax and @Luka-sama?

**Comment by Luka-sama** [comment]
Yes, I think that would be useful.

**Comment by NiklasLeukroth** [comment]
Sorry, I forgot to reply earlier, I am in favor of this change

**Comment by kevinmatthes** [comment]
Okay, thank you for responses!  I will set up Dependabot for all respective repositories as soon as we received the pending feedback.

Has anyone of you heard something about the current progress of the feedback process or has asked the responsible?
